### ISSUE TITLE
Argument and property naming conflict

### ISSUE THREAD

**Issue by kellyselden** [glimmerjs/glimmer-application#80] opened 2017-06-23 20:01 UTC
First of all, don't know if this is the right place.

Given:
```html
<list-component @incoming="Kelly" />
```

```js
import Component from '@glimmer/component';

export default class ListComponent extends Component {
  incoming = "Selden"
};
```

```html
{{@incoming}} {{incoming}}
```

I get "Kelly" with no errors in the console. If I change one of them to "incoming2", I get the expected "Kelly Selden". Reading about the distinction between arguments and properties, it seems like you should be able to reuse a name and not conflict.

**Comment by locks** [comment] 2017-06-24 11:34
I can't reproduce @kellyselden, can you add your package.json?

**Comment by kellyselden** [comment] 2017-06-27 23:10
```js
  "devDependencies": {
    "@glimmer/application": "^0.6.0",
    "@glimmer/application-pipeline": "^0.7.3",
    "@glimmer/blueprint": "^0.4.0",
    "@glimmer/resolver": "^0.3.0",
    "broccoli-asset-rev": "^2.5.0",
    "ember-cli": "^2.14.0-beta.2",
    "ember-cli-inject-live-reload": "^1.6.1",
    "ember-cli-sass": "^6.2.0",
    "ember-cli-uglify": "^1.2.0",
    "typescript": "^2.2.2"
  }
```

**Comment by robbiepitts** [comment] 2017-06-28 01:27
Looks like there's a `@glimmer/compiler` mismatch. `@glimmer/application` has 0.25.1 and `@glimmer/application-pipeline` -> `ember-build-utilities` has 0.24.0-beta.4. I have a PR addressing this (https://github.com/ember-cli/ember-build-utilities/pull/18). This could be the cause of the problem.

**Comment by robbiepitts** [comment] 2017-06-28 01:31
Nah, that's probably not the problem here.

**Comment by tomdale** [comment] 2017-07-08 19:19
Seems to be working for me too. 
[Playground repro](https://glimmer-playground.netlify.com/?app=JTVCJTdCJTIybmFtZSUyMiUzQSUyMm15LWdsaW1tZXItYXBwJTIyJTJDJTIydGVtcGxhdGUlMjIlM0ElN0IlMjJmaWxlTmFtZSUyMiUzQSUyMnNyYyUyRnVpJTJGY29tcG9uZW50cyUyRm15LWdsaW1tZXItYXBwJTJGdGVtcGxhdGUuaGJzJTIyJTJDJTIyc291cmNlVGV4dCUyMiUzQSUyMiUzQ2RpdiUzRSUzQ215LWNvbXBvbmVudCUyMCU0MGluY29taW5nJTNEJTVDJTIyS2VsbHklNUMlMjIlMjAlMkYlM0UlM0MlMkZkaXYlM0UlMjIlN0QlMkMlMjJjb21wb25lbnQlMjIlM0FudWxsJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm15LWNvbXBvbmVudCUyMiUyQyUyMnRlbXBsYXRlJTIyJTNBJTdCJTIyZmlsZU5hbWUlMjIlM0ElMjJzcmMlMkZ1aSUyRmNvbXBvbmVudHMlMkZteS1jb21wb25lbnQlMkZ0ZW1wbGF0ZS5oYnMlMjIlMkMlMjJzb3VyY2VUZXh0JTIyJTNBJTIyJTNDbXktY29tcG9uZW50JTNFJTVDbiUyMCUyMCU3QiU3QiU0MGluY29taW5nJTdEJTdEJTIwJTdCJTdCaW5jb21pbmclN0QlN0QlNUNuJTNDJTJGbXktY29tcG9uZW50JTNFJTIyJTdEJTJDJTIyY29tcG9uZW50JTIyJTNBJTdCJTIyZmlsZU5hbWUlMjIlM0ElMjJzcmMlMkZ1aSUyRmNvbXBvbmVudHMlMkZteS1jb21wb25lbnQlMkZjb21wb25lbnQudHMlMjIlMkMlMjJzb3VyY2VUZXh0JTIyJTNBJTIyaW1wb3J0JTIwQ29tcG9uZW50JTJDJTIwJTdCJTIwdHJhY2tlZCUyMCU3RCUyMGZyb20lMjAlNUMlMjIlNDBnbGltbWVyJTJGY29tcG9uZW50JTVDJTIyJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwY2xhc3MlMjBleHRlbmRzJTIwQ29tcG9uZW50JTIwJTdCJTVDbiUyMCUyMCU0MHRyYWNrZWQlMjBpbmNvbWluZyUyMCUzRCUyMCU1QyUyMlNlbGRlbiU1QyUyMiUzQiU1Q24lN0QlM0IlMjIlN0QlN0QlNUQ=)

**Comment by locks** [comment] 2017-07-09 23:29
@kellyselden I'm closing this due to lack of reproduction. Please ping me and reopen if you still find it a problem 🙏

**Closed by locks** 2017-07-09 23:29 UTC

**Comment by kellyselden** [comment] 2017-07-10 16:30
Just verified not a problem. I can't even reproduce the original failure :man_shrugging:
