### ISSUE TITLE
Difficulties starting new glimmer app

### ISSUE THREAD

**Issue by vaidehijoshi** [glimmerjs/glimmer-application#49] opened 2017-04-05 23:49 UTC
While trying to start a new glimmer app with @lbaillie, we ran into some issues.

We first tried using the `--web-component` option, which returned an error:
```
$  ember new my-app -b @glimmer/blueprint --web-component
The option '--web-component' is not registered with the new command. Run `ember new --help` for a list of supported options.
Error creating new application. Removing generated directory `./my-app`
Unknown blueprint: @glimmer/blueprint
```

And then we tried it again, without the `--web-component` flag, but still no luck:
```
$  ember new my-app -b @glimmer/blueprint
Error creating new application. Removing generated directory `./my-app`
Unknown blueprint: @glimmer/blueprint
```

The only way that we _did_ get it to install as expected was when we used the github repo explicitly, like so:
```
$ ember new my-app -b https://github.com/glimmerjs/glimmer-blueprint.git
```

...But this command didn't work with the `--web-component` flag. Our error looked like this:
```
Command failed: yarn add --dev @glimmer/web-component
warning ember-cli > broccoli-babel-transpiler > babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
yarn add v0.16.1
[1/4] Resolving packages...
```

We were initially using the [install guide](https://glimmerjs.com/guides/installing), but found that we had to uninstall and reinstall `ember-cli` multiple times, using both`npm` and `yarn`. We're guessing that perhaps something wasn't linked correctly? In any case, thought you might want to know (and maybe you can see what we were doing wrong?!) Thanks!

**Comment by robbiepitts** [comment] 2017-04-06 00:10
```
The option '--web-component' is not registered with the new command.
```

This is just a warning, and is related to the fact that one is currently unable to register an option with the `new` command. But it still works. Sorry for the confusion with that. 😃 

```
$  ember new my-app -b @glimmer/blueprint
Error creating new application. Removing generated directory `./my-app`
Unknown blueprint: @glimmer/blueprint
```

This looks like you have the wrong version of ember-cli installed globally. What do you get when you do `ember -v`?

I was unable to get an error with using the beta version of ember-cli:

```
ember new my-app -b https://github.com/glimmerjs/glimmer-blueprint.git --web-component
```

Is that the command you used that produced an error?

**Comment by lbaillie** [comment] 2017-04-06 17:39
Thankfully, we still have our terminal open, and we happened to have run `ember -v` right after getting that error. This was the output at that time:
```
$ ember -v
ember-cli: 2.13.0-beta.3
node: 6.0.0
os: darwin x64
```
And yeah, the last command you mentioned was the one that triggered the last error we mentioned.

Here is the exact order of what we ran in our terminal and what followed, after we got the last error we mentioned:

Immediately after seeing that error, we ran it again without the `--web-component` flag:
```
$ ember new my-app -b https://github.com/glimmerjs/glimmer-blueprint.git
```
This created a new glimmer project just fine. Then:
```
$ yarn global remove ember-cli
$ yarn global add ember-cli/ember-cli
$ which ember
/Users/engineering/.nvm/versions/node/v6.0.0/bin/ember
$ npm uninstall -g ember-cli
$ which ember
/Users/engineering/.nvm/versions/node/v6.0.0/bin/ember
$ sudo npm uninstall -g ember-cli
$ which ember
/Users/engineering/.nvm/versions/node/v6.0.0/bin/ember
$ sudo npm uninstall -g ember-cli
$ sudo npm uninstall -g ember
$ which ember
/Users/engineering/.nvm/versions/node/v6.0.0/bin/ember
$ ls -alt /Users/engineering/.nvm/versions/node/v6.0.0/bin/ember
lrwxrwxr-x  1 engineering  staff  58 Apr  5 16:24 /Users/engineering/.nvm/versions/node/v6.0.0/bin/ember -> ../../../../../.yarn-config/global/node_modules/.bin/ember
$ ember -v
ember-cli: 2.13.0-beta.3
node: 6.0.0
os: darwin x64
$ yarn global remove ember-cli
$ ember -v
zsh: command not found: ember
$ which ember
ember not found
$ yarn global add ember-cli/ember-cli
$ ember -v
ember-cli: 2.13.0-beta.3
node: 6.0.0
os: darwin x64
```
At that point, we ran `ember new my-app -b @glimmer/blueprint` without issue and were able to create a new project.

That's almost definitely more information than you need to know, but hopefully some of it is helpful! 😛

**Comment by tomdale** [comment] 2017-04-06 20:52
@robbiepitts 

> This is just a warning, and is related to the fact that one is currently unable to register an option with the new command. But it still works. Sorry for the confusion with that. 😃

Err, this seems bad. 😬 What's the plan to fix this?

**Comment by robbiepitts** [comment] 2017-04-06 20:56
@tomdale Yes, it is bad. [Here](https://github.com/glimmerjs/glimmer-web-component/issues/9#issuecomment-291571247)'s the issue for it. I could use some help/advice. I have not yet been able to figure out a solution to this. The problem is that `initializeCustomElements` gets the `Application` type from `node_modules/@glimmer/web-component/node_modules/@glimmer/application` but when you _use_ `initializeCustomElements` and pass in an instance of `Application` the type comes from `node_modules/@glimmer/application`.

**Comment by robbiepitts** [comment] 2017-04-07 14:24
Oh, I was obviously very confused. Talking about a different error. Anyhow, the error _I_ was talking about has been fixed in @glimmer/web-component@0.1.1.

The plan for the ember-cli error is TBD. First step is creating an issue for it in ember-cli. According to @rwjblue we are able to register options with the `generate` command, so I'm hoping the fix will just involve borrowing some code. But I've never gotten into ember-cli internals so I don't really know.

**Comment by atrama** [comment] 2017-04-07 16:58
@vaidehijoshi are you still running into this? I also got the error below because my blueprint was installed in a different location than the rest of my global node modules. Moving the blueprint fixed all my issues.

```
Error creating new application. Removing generated directory `./my-app`
Unknown blueprint: @glimmer/blueprint
```

**Comment by vaidehijoshi** [comment] 2017-04-07 22:50
@atrama We were eventually able to create a new Glimmer app, so that `Unknown blueprint: @glimmer/blueprint` error ultimately didn't end up being a blocker for us! But, we figured that it was possible someone else would eventually run into this same problem, so we just wanted to flag it for the team so that they'd be aware of it.

**Comment by crodriguez1a** [comment] 2017-04-14 13:43
@vaidehijoshi @atrama I also ran into this issue. The remote blueprint workaround worked for me as well. It seems like (for at least this iteration) migrating to a global yarn install of ember-cli may be a pre-requisite for using `@glimmer/blueprint`.

**Comment by locks** [comment] 2018-03-05 15:25
I believe this has been addressed upstream. Thank you!

**Closed by locks** 2018-03-05 15:25 UTC
