### ISSUE TITLE
Infinite loop when observing 'args' in a computed property that returns an array that is iterated over by {{#each}}

### ISSUE THREAD

**Issue by DecayConstant** [glimmerjs/glimmer-application#50] opened 2017-04-06 20:22 UTC
```javascript
import Component, {tracked} from "@glimmer/component";
export default class MyComponent extends Component {
    @tracked('args') get arrayTest() {
        console.log('bye');
        return [1, 2];
    }
};
```

```handlebars
<div>
    {{#each arrayTest key='@index' as |num|}}
         {{num}}
    {{/each}}
</div>
```

With the above component, and template, the computed property gets recomputed in an infinite loop.  You'll see `bye` in the console forever.

If you remove `{{num}}` from the inside of the `{{#each}}`, the infinite loop does not happen.

**Comment by robbiepitts** [comment] 2017-04-06 20:30
Thank you! Good find!

Ping @tomdale

**Comment by CvX** [comment] 2017-04-09 01:07
(duplicate of #43)

**Comment by tomdale** [comment] 2017-04-09 18:38
This is a bad bug. Making `args` a tracked property is probably wrong because it means every time we set it during rerender we schedule a rerender. Probably we want to manually dirty the `args` tag instead of using a tracked property which installs a setter that schedules a rerender.

**Comment by tomdale** [comment] 2017-07-08 19:57
This got fixed awhile ago. Thank you for reporting!

**Closed by tomdale** 2017-07-08 19:57 UTC
